package org.gephi.ui.statistics.plugin.social;

import java.awt.Color;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import org.gephi.lib.validation.BetweenZeroAndOneValidator;
import org.gephi.lib.validation.IntegerIntervalValidator;
import org.gephi.lib.validation.PositiveNumberValidator;
import org.jdesktop.swingx.painter.RectanglePainter;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;

/**
 *
 * @author Alexandru Topirceanu
 */
public class DiffusionPanel extends javax.swing.JPanel {

    public DiffusionPanel() {
        initComponents();
//        org.jdesktop.swingx.painter.RectanglePainter rp = new RectanglePainter(Color.black, Color.black);
//        header.setBackgroundPainter(rp);
    }

    public static ValidationPanel createValidationPanel(DiffusionPanel innerPanel) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new DiffusionPanel();
        }
        validationPanel.setInnerComponent(innerPanel);

        ValidationGroup group = validationPanel.getValidationGroup();

        // graph parameters
        group.add(innerPanel.tAnimation, Validators.REQUIRE_NON_EMPTY_STRING, new IntegerIntervalValidator(1, 100));

        return validationPanel;
    }

    protected void selectModel(int diffuse) {
        switch (diffuse) {
            case 0:
                radioDSimple.setSelected(true);
                break;
            case 1:
                radioDComplex.setSelected(true);
                break;
            case 2:
                radioCSimple.setSelected(true);
                break;
            case 3:
                radioCComplex.setSelected(true);
                break;
            default:
                break;
        }
    }

    protected int getSelectedModel() {
        return radioDSimple.isSelected() ? 0
                : radioDComplex.isSelected() ? 1
                : radioCSimple.isSelected() ? 2
                : radioCComplex.isSelected() ? 3 : -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        labelRandomize1 = new javax.swing.JLabel();
        desriptionLabel = new org.jdesktop.swingx.JXLabel();
        header = new org.jdesktop.swingx.JXHeader();
        tAnimation = new javax.swing.JTextField();
        lDiffuse = new javax.swing.JLabel();
        labelResolution = new org.jdesktop.swingx.JXLabel();
        diffAnimateCheckBox = new javax.swing.JCheckBox();
        labelResolution1 = new org.jdesktop.swingx.JXLabel();
        jSeparator1 = new javax.swing.JSeparator();
        radioDSimple = new javax.swing.JRadioButton();
        radioCSimple = new javax.swing.JRadioButton();
        radioDComplex = new javax.swing.JRadioButton();
        lDiffuse1 = new javax.swing.JLabel();
        lDiffuse2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lDiffuse3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lDiffuse4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lDiffuse5 = new javax.swing.JLabel();
        lDiffuse6 = new javax.swing.JLabel();
        radioCComplex = new javax.swing.JRadioButton();
        lDiffuse7 = new javax.swing.JLabel();

        labelRandomize1.setFont(labelRandomize1.getFont().deriveFont(labelRandomize1.getFont().getSize()-1f));
        labelRandomize1.setForeground(new java.awt.Color(102, 102, 102));
        labelRandomize1.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.labelRandomize1.text")); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 127, 39));

        desriptionLabel.setLineWrap(true);
        desriptionLabel.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.desriptionLabel.text")); // NOI18N
        desriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        header.setDescription(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.header.description")); // NOI18N
        header.setDescriptionForeground(new java.awt.Color(255, 127, 39));
        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gephi/ui/statistics/plugin/social/SigmaLogo2.png"))); // NOI18N
        header.setIconPosition(org.jdesktop.swingx.JXHeader.IconPosition.LEFT);
        header.setTitle(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.header.title")); // NOI18N
        header.setTitleForeground(new java.awt.Color(255, 127, 39));
        header.setBackground(new java.awt.Color(0, 0, 0));
        header.setBackgroundPainter(new RectanglePainter(Color.black, Color.black));

        tAnimation.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.tAnimation.text")); // NOI18N
        tAnimation.setToolTipText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.tAnimation.toolTipText")); // NOI18N

        lDiffuse.setFont(lDiffuse.getFont().deriveFont(lDiffuse.getFont().getSize()-1f));
        lDiffuse.setForeground(new java.awt.Color(102, 102, 102));
        lDiffuse.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.lDiffuse.text")); // NOI18N
        lDiffuse.setFocusable(false);

        labelResolution.setForeground(new java.awt.Color(102, 102, 102));
        labelResolution.setLineWrap(true);
        labelResolution.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.labelResolution.text")); // NOI18N
        labelResolution.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelResolution.setFont(labelResolution.getFont().deriveFont(labelResolution.getFont().getSize()-1f));
        labelResolution.setPreferredSize(new java.awt.Dimension(500, 12));

        diffAnimateCheckBox.setSelected(true);
        diffAnimateCheckBox.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.diffAnimateCheckBox.text")); // NOI18N
        diffAnimateCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        diffAnimateCheckBox.setOpaque(false);

        labelResolution1.setForeground(new java.awt.Color(102, 102, 102));
        labelResolution1.setLineWrap(true);
        labelResolution1.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.labelResolution1.text")); // NOI18N
        labelResolution1.setFont(labelResolution1.getFont().deriveFont(labelResolution1.getFont().getSize()-1f));
        labelResolution1.setPreferredSize(new java.awt.Dimension(500, 12));

        jSeparator1.setForeground(new java.awt.Color(255, 127, 39));

        buttonGroup1.add(radioDSimple);
        radioDSimple.setSelected(true);
        radioDSimple.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.radioDSimple.text")); // NOI18N
        radioDSimple.setOpaque(false);

        buttonGroup1.add(radioCSimple);
        radioCSimple.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.radioCSimple.text")); // NOI18N
        radioCSimple.setOpaque(false);

        buttonGroup1.add(radioDComplex);
        radioDComplex.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.radioDComplex.text")); // NOI18N
        radioDComplex.setToolTipText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.radioDComplex.toolTipText")); // NOI18N
        radioDComplex.setActionCommand(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.radioDComplex.actionCommand")); // NOI18N
        radioDComplex.setOpaque(false);

        lDiffuse1.setFont(lDiffuse1.getFont().deriveFont(lDiffuse1.getFont().getSize()-1f));
        lDiffuse1.setForeground(new java.awt.Color(102, 102, 102));
        lDiffuse1.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.lDiffuse1.text")); // NOI18N
        lDiffuse1.setFocusable(false);

        lDiffuse2.setFont(lDiffuse2.getFont().deriveFont(lDiffuse2.getFont().getSize()-1f));
        lDiffuse2.setForeground(new java.awt.Color(102, 102, 102));
        lDiffuse2.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.lDiffuse2.text")); // NOI18N
        lDiffuse2.setFocusable(false);

        jSeparator3.setForeground(new java.awt.Color(255, 127, 39));

        lDiffuse3.setFont(lDiffuse3.getFont().deriveFont(lDiffuse3.getFont().getSize()-1f));
        lDiffuse3.setForeground(new java.awt.Color(255, 127, 39));
        lDiffuse3.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.lDiffuse3.text")); // NOI18N
        lDiffuse3.setFocusable(false);

        jSeparator4.setForeground(new java.awt.Color(255, 127, 39));

        lDiffuse4.setFont(lDiffuse4.getFont().deriveFont(lDiffuse4.getFont().getSize()-1f));
        lDiffuse4.setForeground(new java.awt.Color(102, 102, 102));
        lDiffuse4.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.lDiffuse4.text")); // NOI18N
        lDiffuse4.setFocusable(false);

        jSeparator5.setForeground(new java.awt.Color(255, 127, 39));

        jSeparator6.setForeground(new java.awt.Color(255, 127, 39));

        lDiffuse5.setFont(lDiffuse5.getFont().deriveFont(lDiffuse5.getFont().getSize()-1f));
        lDiffuse5.setForeground(new java.awt.Color(255, 127, 39));
        lDiffuse5.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.lDiffuse5.text")); // NOI18N
        lDiffuse5.setFocusable(false);

        lDiffuse6.setFont(lDiffuse6.getFont().deriveFont(lDiffuse6.getFont().getSize()-1f));
        lDiffuse6.setForeground(new java.awt.Color(102, 102, 102));
        lDiffuse6.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.lDiffuse6.text")); // NOI18N
        lDiffuse6.setFocusable(false);

        buttonGroup1.add(radioCComplex);
        radioCComplex.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.radioCComplex.text")); // NOI18N
        radioCComplex.setOpaque(false);

        lDiffuse7.setFont(lDiffuse7.getFont().deriveFont(lDiffuse7.getFont().getSize()-1f));
        lDiffuse7.setForeground(new java.awt.Color(102, 102, 102));
        lDiffuse7.setText(org.openide.util.NbBundle.getMessage(DiffusionPanel.class, "DiffusionPanel.lDiffuse7.text_1")); // NOI18N
        lDiffuse7.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diffAnimateCheckBox))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelResolution1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(39, 39, 39))
                            .addComponent(labelResolution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioCComplex)
                                .addGap(18, 18, 18)
                                .addComponent(lDiffuse7, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioCSimple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lDiffuse2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(694, 694, 694)
                        .addComponent(desriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(lDiffuse3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lDiffuse4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDiffuse5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lDiffuse6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioDSimple))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jSeparator4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(lDiffuse1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 43, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioDComplex)
                                        .addGap(18, 18, 18)
                                        .addComponent(lDiffuse, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lDiffuse4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lDiffuse3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDSimple)
                    .addComponent(lDiffuse1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDComplex)
                    .addComponent(lDiffuse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lDiffuse6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lDiffuse5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCSimple)
                    .addComponent(lDiffuse2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCComplex)
                    .addComponent(lDiffuse7))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diffAnimateCheckBox)
                    .addComponent(labelResolution1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelResolution, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(desriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private org.jdesktop.swingx.JXLabel desriptionLabel;
    protected javax.swing.JCheckBox diffAnimateCheckBox;
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lDiffuse;
    private javax.swing.JLabel lDiffuse1;
    private javax.swing.JLabel lDiffuse2;
    private javax.swing.JLabel lDiffuse3;
    private javax.swing.JLabel lDiffuse4;
    private javax.swing.JLabel lDiffuse5;
    private javax.swing.JLabel lDiffuse6;
    private javax.swing.JLabel lDiffuse7;
    private javax.swing.JLabel labelRandomize1;
    private org.jdesktop.swingx.JXLabel labelResolution;
    private org.jdesktop.swingx.JXLabel labelResolution1;
    protected javax.swing.JRadioButton radioCComplex;
    protected javax.swing.JRadioButton radioCSimple;
    protected javax.swing.JRadioButton radioDComplex;
    protected javax.swing.JRadioButton radioDSimple;
    protected javax.swing.JTextField tAnimation;
    // End of variables declaration//GEN-END:variables
}
