package org.gephi.ui.statistics.plugin.social;

import javax.swing.JCheckBox;
import org.gephi.lib.validation.BetweenZeroAndOneValidator;
import org.gephi.lib.validation.IntegerIntervalValidator;
import org.gephi.lib.validation.PositiveNumberValidator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;

/**
 *
 * @author Alexandru Topirceanu
 */
public class SocializePanel extends javax.swing.JPanel {

    public SocializePanel() {
        initComponents();
    }
   
    public static ValidationPanel createValidationPanel(SocializePanel innerPanel) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new SocializePanel();
        }
        validationPanel.setInnerComponent(innerPanel);

        ValidationGroup group = validationPanel.getValidationGroup();       

        return validationPanel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        labelRandomize1 = new javax.swing.JLabel();
        desriptionLabel = new org.jdesktop.swingx.JXLabel();
        header = new org.jdesktop.swingx.JXHeader();
        bKeepColor = new javax.swing.JRadioButton();
        bDontKeepColor = new javax.swing.JRadioButton();
        labelRandomize2 = new javax.swing.JLabel();
        labelRandomize3 = new javax.swing.JLabel();

        labelRandomize1.setFont(labelRandomize1.getFont().deriveFont(labelRandomize1.getFont().getSize()-1f));
        labelRandomize1.setForeground(new java.awt.Color(102, 102, 102));
        labelRandomize1.setText(org.openide.util.NbBundle.getMessage(SocializePanel.class, "SocializePanel.labelRandomize1.text")); // NOI18N

        setForeground(new java.awt.Color(51, 51, 255));

        desriptionLabel.setLineWrap(true);
        desriptionLabel.setText(org.openide.util.NbBundle.getMessage(SocializePanel.class, "SocializePanel.desriptionLabel.text")); // NOI18N
        desriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        header.setDescription(org.openide.util.NbBundle.getMessage(SocializePanel.class, "SocializePanel.header.description")); // NOI18N
        header.setTitle(org.openide.util.NbBundle.getMessage(SocializePanel.class, "SocializePanel.header.title")); // NOI18N

        buttonGroup1.add(bKeepColor);
        bKeepColor.setSelected(true);
        bKeepColor.setText(org.openide.util.NbBundle.getMessage(SocializePanel.class, "SocializePanel.bKeepColor.text")); // NOI18N

        buttonGroup1.add(bDontKeepColor);
        bDontKeepColor.setText(org.openide.util.NbBundle.getMessage(SocializePanel.class, "SocializePanel.bDontKeepColor.text")); // NOI18N

        labelRandomize2.setFont(labelRandomize2.getFont().deriveFont(labelRandomize2.getFont().getSize()-1f));
        labelRandomize2.setForeground(new java.awt.Color(102, 102, 102));
        labelRandomize2.setText(org.openide.util.NbBundle.getMessage(SocializePanel.class, "SocializePanel.labelRandomize2.text")); // NOI18N

        labelRandomize3.setFont(labelRandomize3.getFont().deriveFont(labelRandomize3.getFont().getSize()-1f));
        labelRandomize3.setForeground(new java.awt.Color(102, 102, 102));
        labelRandomize3.setText(org.openide.util.NbBundle.getMessage(SocializePanel.class, "SocializePanel.labelRandomize3.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(desriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(391, 391, 391))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDontKeepColor)
                    .addComponent(bKeepColor))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRandomize2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRandomize3, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bKeepColor)
                    .addComponent(labelRandomize2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDontKeepColor)
                    .addComponent(labelRandomize3))
                .addGap(32, 32, 32)
                .addComponent(desriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JRadioButton bDontKeepColor;
    protected javax.swing.JRadioButton bKeepColor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private org.jdesktop.swingx.JXLabel desriptionLabel;
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JLabel labelRandomize1;
    private javax.swing.JLabel labelRandomize2;
    private javax.swing.JLabel labelRandomize3;
    // End of variables declaration//GEN-END:variables
}
