package org.deltaalex.fractaldimension.ui;

/**
 *
 * @author Alexandru Topirceanu
 */
public class FractalDimensionPanel extends javax.swing.JPanel {

    public FractalDimensionPanel() {
        initComponents();
    }

    public boolean isDirected() {
        return jRadioDirected.isSelected();
    }

    public void setDirected(boolean directed) {
        bGroup.setSelected(directed ? jRadioDirected.getModel() : jRadioUndirected.getModel(), true);
        if (!directed) {
            jRadioDirected.setEnabled(false);
        }
    }

    public int getMinBoxes() {
        // use default setting
        if (checkBoxes.isSelected()) {
            return -1;
        }

        try {
            return Integer.parseInt(tMinBoxes.getText().trim());
        } catch (Exception e) {
            return 1;
        }
    }

    public void setMinBoxes(int minBoxes) {
        tMinBoxes.setText(Integer.toString(minBoxes));
    }

    public int getMaxBoxes() {
        // use default setting
        if (checkBoxes.isSelected()) {
            return -1;
        }

        try {
            return Integer.parseInt(tMaxBoxes.getText().trim());
        } catch (Exception e) {
            return 10;
        }
    }

    public void setMaxBoxes(int maxBoxes) {
        tMaxBoxes.setText(Integer.toString(maxBoxes));
    }

    public boolean getCheckCores() {
        return checkCores.isSelected();
    }

    public void setCheckCores(boolean checkCores) {
        this.checkCores.setSelected(checkCores);

        tCores.setEnabled(!checkCores);
    }

    public int getCores() {
        // use default setting
        if (checkCores.isSelected()) {
            return -1;
        }

        try {
            return Integer.parseInt(tCores.getText().trim());
        } catch (Exception e) {
            return 4;
        }
    }

    public void setCores(int cores) {
        tCores.setText(Integer.toString(cores));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroup = new javax.swing.ButtonGroup();
        header = new org.jdesktop.swingx.JXHeader();
        tMinBoxes = new javax.swing.JTextField();
        tMaxBoxes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkCores = new javax.swing.JCheckBox();
        tCores = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioDirected = new javax.swing.JRadioButton();
        jRadioUndirected = new javax.swing.JRadioButton();
        checkBoxes = new javax.swing.JCheckBox();

        header.setDescription(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "ModularityPanel.header.description")); // NOI18N
        header.setTitle(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "ModularityPanel.header.title")); // NOI18N
        header.setToolTipText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.header.toolTipText")); // NOI18N

        tMinBoxes.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.tMinBoxes.text")); // NOI18N
        tMinBoxes.setEnabled(false);

        tMaxBoxes.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.tMaxBoxes.text")); // NOI18N
        tMaxBoxes.setEnabled(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.jLabel2.text")); // NOI18N

        checkCores.setSelected(true);
        checkCores.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.checkCores.text")); // NOI18N
        checkCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCoresActionPerformed(evt);
            }
        });

        tCores.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.tCores.text")); // NOI18N
        tCores.setEnabled(false);

        jLabel3.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.jLabel3.text")); // NOI18N

        bGroup.add(jRadioDirected);
        jRadioDirected.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.jRadioDirected.text")); // NOI18N

        bGroup.add(jRadioUndirected);
        jRadioUndirected.setSelected(true);
        jRadioUndirected.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.jRadioUndirected.text")); // NOI18N

        checkBoxes.setSelected(true);
        checkBoxes.setText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.checkBoxes.text")); // NOI18N
        checkBoxes.setToolTipText(org.openide.util.NbBundle.getMessage(FractalDimensionPanel.class, "FractalDimensionPanel.checkBoxes.toolTipText")); // NOI18N
        checkBoxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioDirected)
                            .addComponent(jRadioUndirected))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkCores)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tCores, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tMinBoxes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tMaxBoxes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxes)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioDirected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioUndirected))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkCores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(checkBoxes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMinBoxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMaxBoxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCoresActionPerformed

        tCores.setEnabled(!checkCores.isSelected());
    }//GEN-LAST:event_checkCoresActionPerformed

    private void checkBoxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxesActionPerformed
        tMinBoxes.setEnabled(!checkBoxes.isSelected());
        tMaxBoxes.setEnabled(!checkBoxes.isSelected());
    }//GEN-LAST:event_checkBoxesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.ButtonGroup bGroup;
    protected javax.swing.JCheckBox checkBoxes;
    protected javax.swing.JCheckBox checkCores;
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    protected javax.swing.JRadioButton jRadioDirected;
    protected javax.swing.JRadioButton jRadioUndirected;
    protected javax.swing.JTextField tCores;
    protected javax.swing.JTextField tMaxBoxes;
    protected javax.swing.JTextField tMinBoxes;
    // End of variables declaration//GEN-END:variables
}
