package org.gephi.ui.generator.plugin;

import org.gephi.lib.validation.BetweenZeroAndOneValidator;
import org.gephi.lib.validation.PositiveNumberValidator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;

/**
 *
 * @author Alexandru Topirceanu
 */
public class CellularGraphPanel extends javax.swing.JPanel {

    /** Creates new form RandomGraphPanel */
    public CellularGraphPanel() {
        initComponents();
    }

    public static ValidationPanel createValidationPanel(CellularGraphPanel innerPanel) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new CellularGraphPanel();
        }
        validationPanel.setInnerComponent(innerPanel);

        ValidationGroup group = validationPanel.getValidationGroup();

        //Node field
        group.add(innerPanel.cellField, Validators.REQUIRE_NON_EMPTY_STRING,
                new PositiveNumberValidator());

        //Edge field
        group.add(innerPanel.intraEdgeField, Validators.REQUIRE_NON_EMPTY_STRING,
                new BetweenZeroAndOneValidator());

        return validationPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodeLabel = new javax.swing.JLabel();
        edgeLabel = new javax.swing.JLabel();
        cellField = new javax.swing.JTextField();
        intraEdgeField = new javax.swing.JTextField();
        edgeLabel1 = new javax.swing.JLabel();
        interEdgeField = new javax.swing.JTextField();
        edgeLabel2 = new javax.swing.JLabel();
        cellSizeField = new javax.swing.JTextField();

        nodeLabel.setText(org.openide.util.NbBundle.getMessage(CellularGraphPanel.class, "CellularGraphPanel.nodeLabel.text")); // NOI18N

        edgeLabel.setText(org.openide.util.NbBundle.getMessage(CellularGraphPanel.class, "CellularGraphPanel.edgeLabel.text")); // NOI18N

        cellField.setText(org.openide.util.NbBundle.getMessage(CellularGraphPanel.class, "CellularGraphPanel.cellField.text")); // NOI18N

        intraEdgeField.setText(org.openide.util.NbBundle.getMessage(CellularGraphPanel.class, "CellularGraphPanel.intraEdgeField.text")); // NOI18N

        edgeLabel1.setText(org.openide.util.NbBundle.getMessage(CellularGraphPanel.class, "CellularGraphPanel.edgeLabel1.text")); // NOI18N

        interEdgeField.setText(org.openide.util.NbBundle.getMessage(CellularGraphPanel.class, "CellularGraphPanel.interEdgeField.text")); // NOI18N

        edgeLabel2.setText(org.openide.util.NbBundle.getMessage(CellularGraphPanel.class, "CellularGraphPanel.edgeLabel2.text")); // NOI18N

        cellSizeField.setText(org.openide.util.NbBundle.getMessage(CellularGraphPanel.class, "CellularGraphPanel.cellSizeField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nodeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edgeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edgeLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edgeLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cellSizeField)
                    .addComponent(intraEdgeField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(interEdgeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intraEdgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edgeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interEdgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edgeLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edgeLabel2))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField cellField;
    protected javax.swing.JTextField cellSizeField;
    private javax.swing.JLabel edgeLabel;
    private javax.swing.JLabel edgeLabel1;
    private javax.swing.JLabel edgeLabel2;
    protected javax.swing.JTextField interEdgeField;
    protected javax.swing.JTextField intraEdgeField;
    private javax.swing.JLabel nodeLabel;
    // End of variables declaration//GEN-END:variables
}
