package org.gephi.ui.generator.plugin;

import javax.swing.JCheckBox;
import org.gephi.lib.validation.BetweenZeroAndOneValidator;
import org.gephi.lib.validation.IntegerIntervalValidator;
import org.gephi.lib.validation.PositiveNumberValidator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;

/**
 *
 * @author Alexandru Topirceanu
 */
public class SzendroiGraphPanel extends javax.swing.JPanel {

    private static final int minNodeDelay = 1;
    private static final int maxNodeDelay = 500;
    private static final int minEdgeDelay = 1;
    private static final int maxEdgeDelay = 100;
    
    /**
     * Creates new form RandomGraphPanel
     */
    public SzendroiGraphPanel() {
        initComponents();
    }

    public static ValidationPanel createValidationPanel(SzendroiGraphPanel innerPanel) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new SzendroiGraphPanel();
        }
        validationPanel.setInnerComponent(innerPanel);

        ValidationGroup group = validationPanel.getValidationGroup();

        // graph parameters
        group.add(innerPanel.sizeField, Validators.REQUIRE_NON_EMPTY_STRING, new PositiveNumberValidator());       
        group.add(innerPanel.seedSizeField, Validators.REQUIRE_NON_EMPTY_STRING, new PositiveNumberValidator());       
        group.add(innerPanel.seedWiringField, Validators.REQUIRE_NON_EMPTY_STRING, new BetweenZeroAndOneValidator());       
        // animation parameters
        group.add(innerPanel.tAnimateNode, Validators.REQUIRE_NON_EMPTY_STRING, new IntegerIntervalValidator(minNodeDelay, maxNodeDelay));
        group.add(innerPanel.tAnimateEdge, Validators.REQUIRE_NON_EMPTY_STRING, new IntegerIntervalValidator(minEdgeDelay, maxEdgeDelay));

        return validationPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weightsGroup = new javax.swing.ButtonGroup();
        nodeLabel = new javax.swing.JLabel();
        sizeField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        animateCheckBox = new javax.swing.JCheckBox();
        labelResolution = new org.jdesktop.swingx.JXLabel();
        tAnimateNode = new javax.swing.JTextField();
        labelResolution1 = new org.jdesktop.swingx.JXLabel();
        tAnimateEdge = new javax.swing.JTextField();
        labelResolution2 = new org.jdesktop.swingx.JXLabel();
        labelResolution3 = new org.jdesktop.swingx.JXLabel();
        radioNoWeights = new javax.swing.JRadioButton();
        radioNormalWeights = new javax.swing.JRadioButton();
        radioPowerWeights = new javax.swing.JRadioButton();
        nodeLabel1 = new javax.swing.JLabel();
        seedSizeField = new javax.swing.JTextField();
        nodeLabel2 = new javax.swing.JLabel();
        seedWiringField = new javax.swing.JTextField();
        checkDegree = new javax.swing.JCheckBox();
        checkBetweenness = new javax.swing.JCheckBox();
        nodeLabel3 = new javax.swing.JLabel();
        checkCloseness = new javax.swing.JCheckBox();
        checkCentrality = new javax.swing.JCheckBox();
        checkClustering = new javax.swing.JCheckBox();
        nodeLabel4 = new javax.swing.JLabel();
        degreeField = new javax.swing.JTextField();
        nodeLabel5 = new javax.swing.JLabel();

        nodeLabel.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.nodeLabel.text_2_2")); // NOI18N

        sizeField.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.sizeField.text_1")); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 204));

        animateCheckBox.setSelected(true);
        animateCheckBox.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.animateCheckBox.text_2")); // NOI18N
        animateCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                animateCheckBoxStateChanged(evt);
            }
        });

        labelResolution.setForeground(new java.awt.Color(102, 102, 102));
        labelResolution.setLineWrap(true);
        labelResolution.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.labelResolution.text_2")); // NOI18N
        labelResolution.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelResolution.setFont(labelResolution.getFont().deriveFont(labelResolution.getFont().getSize()-1f));
        labelResolution.setPreferredSize(new java.awt.Dimension(500, 12));

        tAnimateNode.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.tAnimateNode.text_2")); // NOI18N

        labelResolution1.setForeground(new java.awt.Color(102, 102, 102));
        labelResolution1.setLineWrap(true);
        labelResolution1.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.labelResolution1.text_2")); // NOI18N
        labelResolution1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelResolution1.setFont(labelResolution1.getFont().deriveFont(labelResolution1.getFont().getSize()-1f));
        labelResolution1.setPreferredSize(new java.awt.Dimension(500, 12));

        tAnimateEdge.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.tAnimateEdge.text_2")); // NOI18N

        labelResolution2.setForeground(new java.awt.Color(102, 102, 102));
        labelResolution2.setLineWrap(true);
        labelResolution2.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.labelResolution2.text_2")); // NOI18N
        labelResolution2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelResolution2.setFont(labelResolution2.getFont().deriveFont(labelResolution2.getFont().getSize()-1f));
        labelResolution2.setPreferredSize(new java.awt.Dimension(500, 12));

        labelResolution3.setForeground(new java.awt.Color(0, 0, 204));
        labelResolution3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelResolution3.setLineWrap(true);
        labelResolution3.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.labelResolution3.text_2")); // NOI18N
        labelResolution3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelResolution3.setFont(labelResolution3.getFont().deriveFont(labelResolution3.getFont().getSize()-1f));
        labelResolution3.setPreferredSize(new java.awt.Dimension(500, 12));

        weightsGroup.add(radioNoWeights);
        radioNoWeights.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.radioNoWeights.text")); // NOI18N

        weightsGroup.add(radioNormalWeights);
        radioNormalWeights.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.radioNormalWeights.text")); // NOI18N

        weightsGroup.add(radioPowerWeights);
        radioPowerWeights.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.radioPowerWeights.text")); // NOI18N

        nodeLabel1.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.nodeLabel1.text_2")); // NOI18N

        seedSizeField.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.seedSizeField.text")); // NOI18N

        nodeLabel2.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.nodeLabel2.text_2")); // NOI18N

        seedWiringField.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.seedWiringField.text")); // NOI18N

        checkDegree.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.checkDegree.text")); // NOI18N

        checkBetweenness.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.checkBetweenness.text")); // NOI18N

        nodeLabel3.setForeground(new java.awt.Color(0, 51, 255));
        nodeLabel3.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.nodeLabel3.text_2")); // NOI18N

        checkCloseness.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.checkCloseness.text")); // NOI18N

        checkCentrality.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.checkCentrality.text")); // NOI18N

        checkClustering.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.checkClustering.text")); // NOI18N

        nodeLabel4.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.nodeLabel4.text_2")); // NOI18N

        degreeField.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.degreeField.text")); // NOI18N
        degreeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeFieldActionPerformed(evt);
            }
        });

        nodeLabel5.setForeground(new java.awt.Color(0, 51, 255));
        nodeLabel5.setText(org.openide.util.NbBundle.getMessage(SzendroiGraphPanel.class, "SzendroiGraphPanel.nodeLabel5.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelResolution3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(animateCheckBox)
                                    .addComponent(tAnimateNode, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tAnimateEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelResolution, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelResolution1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelResolution2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioNormalWeights)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkDegree)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkBetweenness)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkCentrality)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkCloseness)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkClustering))
                            .addComponent(radioPowerWeights)
                            .addComponent(nodeLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nodeLabel)
                                    .addComponent(nodeLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nodeLabel1)
                                    .addComponent(nodeLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seedSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seedWiringField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(radioNoWeights)
                            .addComponent(nodeLabel5))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeLabel)
                    .addComponent(nodeLabel1)
                    .addComponent(seedSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeLabel2)
                    .addComponent(seedWiringField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degreeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(nodeLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioNoWeights)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioNormalWeights)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioPowerWeights)
                .addGap(29, 29, 29)
                .addComponent(nodeLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDegree)
                    .addComponent(checkBetweenness)
                    .addComponent(checkCentrality)
                    .addComponent(checkCloseness)
                    .addComponent(checkClustering))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelResolution, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animateCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tAnimateNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelResolution1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tAnimateEdge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelResolution2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelResolution3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void animateCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_animateCheckBoxStateChanged
        tAnimateNode.setEnabled(((JCheckBox) evt.getSource()).isSelected());
        tAnimateEdge.setEnabled(((JCheckBox) evt.getSource()).isSelected());
    }//GEN-LAST:event_animateCheckBoxStateChanged

    private void degreeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox animateCheckBox;
    protected javax.swing.JCheckBox checkBetweenness;
    protected javax.swing.JCheckBox checkCentrality;
    protected javax.swing.JCheckBox checkCloseness;
    protected javax.swing.JCheckBox checkClustering;
    protected javax.swing.JCheckBox checkDegree;
    protected javax.swing.JTextField degreeField;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXLabel labelResolution;
    private org.jdesktop.swingx.JXLabel labelResolution1;
    private org.jdesktop.swingx.JXLabel labelResolution2;
    private org.jdesktop.swingx.JXLabel labelResolution3;
    private javax.swing.JLabel nodeLabel;
    private javax.swing.JLabel nodeLabel1;
    private javax.swing.JLabel nodeLabel2;
    private javax.swing.JLabel nodeLabel3;
    private javax.swing.JLabel nodeLabel4;
    private javax.swing.JLabel nodeLabel5;
    protected javax.swing.JRadioButton radioNoWeights;
    protected javax.swing.JRadioButton radioNormalWeights;
    protected javax.swing.JRadioButton radioPowerWeights;
    protected javax.swing.JTextField seedSizeField;
    protected javax.swing.JTextField seedWiringField;
    protected javax.swing.JTextField sizeField;
    protected javax.swing.JTextField tAnimateEdge;
    protected javax.swing.JTextField tAnimateNode;
    protected javax.swing.ButtonGroup weightsGroup;
    // End of variables declaration//GEN-END:variables
}
